# Generated by Django 4.1 on 2022-10-25 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 25, 18, 37, 13, 856623, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 25, 18, 37, 13, 856623, tzinfo=datetime.timezone.utc)),
        ),
    ]
